### ISSUE TITLE
Problems making Glossaries

### ISSUE THREAD

**Issue by lars-seelbach** [astoeckel/smart-thesis#4]
I had some trouble compiling the demo with working glossaries.
The .gls file was not created and a warning that 'wolf' was referenced but not defined got printed.
Finally the accepted answer on this page helped:
https://tex.stackexchange.com/questions/1226/how-to-make-latexmk-use-makeglossaries

I prepended the following lines to latexmkrc and it worked.

```
add_cus_dep('glo', 'gls', 0, 'makeglo2gls');
sub makeglo2gls {
    system("makeindex -s '$_[0]'.ist -t '$_[0]'.glg -o '$_[0]'.gls '$_[0]'.glo");
}
```

**Comment by astoeckel** [comment]
Thank you for reporting this issue!

I can confirm that it doesn't work as it should. Apparently, I've used the code you've posted in my master thesis as well (https://github.com/astoeckel/master-thesis-astoeckel-2015/blob/master/latexmkrc), so I've added it to the repository.
